Repository mash-up-kr/mobalmobal_iOS, pull requests merged in 2021-05, with the labels that each got.

#114 (#40) (#112) 설정 기능 추가 및 내 계좌UI구현
  MobalMobal/MobalMobal.xcodeproj/project.pbxproj
  MobalMobal/MobalMobal/Assets.xcassets/iconlyBank.imageset/Contents.json
  MobalMobal/MobalMobal/Assets.xcassets/iconlyBank.imageset/iconlyBank.png
  MobalMobal/MobalMobal/Assets.xcassets/iconlyBank.imageset/iconlyBank@2x.png
  MobalMobal/MobalMobal/Assets.xcassets/iconlyBank.imageset/iconlyBank@3x.png
  MobalMobal/MobalMobal/Assets.xcassets/iconlyBankAccoun.imageset/Contents.json
  MobalMobal/MobalMobal/Assets.xcassets/iconlyBankAccoun.imageset/iconlyBankAccoun.png
  MobalMobal/MobalMobal/Assets.xcassets/iconlyBankAccoun.imageset/iconlyBankAccoun@2x.png
  MobalMobal/MobalMobal/Assets.xcassets/iconlyBankAccoun.imageset/iconlyBankAccoun@3x.png
  MobalMobal/MobalMobal/Info.plist
  MobalMobal/MobalMobal/SceneDelegate.swift
  MobalMobal/MobalMobal/Setting/MyAccountViewController.swift
  MobalMobal/MobalMobal/Setting/SettingTableViewCell.swift
  MobalMobal/MobalMobal/Setting/SettingViewController.swift
  MobalMobal/MobalMobal/Setting/WebviewController.swift
  MobalMobal/MobalMobal/ViewController.swift
Labels: UI 작업, 기능 추가

#111 (#18) 프로필에서 각 뷰로 이동하는 flow추가
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewController.swift
  MobalMobal/MobalMobal/Profile/Cell/ProfileDonatingTableViewCell.swift
  MobalMobal/MobalMobal/Profile/Cell/ProfileTableViewCell.swift
  MobalMobal/MobalMobal/Profile/ViewController/ProfileViewController.swift
  MobalMobal/MobalMobal/Profile/ViewModel/ProfileViewModel.swift
  MobalMobal/MobalMobal/ViewController.swift
Labels: 기능 추가

#117 (#115) CollectionViewCell 재사용으로 인한 이미지 적용문제 해결 (Feature/cell image download)
  MobalMobal/MobalMobal/Main/MainViewController.swift
  MobalMobal/MobalMobal/Main/cell/MainOngoingDonationCollectionViewCell.swift
Labels: UI 작업

#123 (#119), (#121) Main에서 내 도네이션 네트워킹, 내 도네이션 네트워킹 구조 변경해서 프로필에 적용
  MobalMobal/MobalMobal/Main/MainViewController.swift
  MobalMobal/MobalMobal/Main/MainViewModel.swift
  MobalMobal/MobalMobal/Main/cell/MainMyDonationCollectionViewCell.swift
  MobalMobal/MobalMobal/Main/cell/MainMyOngoingDonationCollectionViewCell.swift
  MobalMobal/MobalMobal/Profile/Cell/ProfileMyDonationTableViewCell.swift
  MobalMobal/MobalMobal/Profile/Cell/ProfileTableViewCell.swift
  MobalMobal/MobalMobal/Profile/ViewController/ProfileViewController.swift
  MobalMobal/MobalMobal/Profile/ViewModel/ProfileMydonationViewModel.swift
  MobalMobal/MobalMobal/Profile/ViewModel/ProfileViewModel.swift
Labels: 기능 추가, 버그

#120 (#107) [상세페이지] 올바른 정보 표시 및 UI 개선 (Feature/detail UI)
  MobalMobal/MobalMobal/DonateComplete/DonateCompleteViewController.swift
  MobalMobal/MobalMobal/DonateMoney/DonateMoneyViewController.swift
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewController+Layout.swift
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewController.swift
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewModel.swift
  MobalMobal/MobalMobal/DonationDetail/Model/DonationDetailResponse.swift
  MobalMobal/MobalMobal/Extension/UIColor+Additions.swift
  MobalMobal/MobalMobal/Extension/UIViewController+Extension.swift
  MobalMobal/MobalMobal/Main/MainViewController.swift
  MobalMobal/MobalMobal/Main/cell/MainOngoingDonationCollectionViewCell.swift
  MobalMobal/MobalMobal/MakeComplete/MakeCompleteViewController.swift
  MobalMobal/MobalMobal/Profile/Cell/ProfileDonatingTableViewCell.swift
  MobalMobal/MobalMobal/ViewController.swift
Labels: UI 작업

#125 (#21) 내 계좌정보 변경
  MobalMobal/MobalMobal.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MobalMobal/MobalMobal/Account/AccountViewController.swift
Labels: UI 작업

#122 (#35) 후원완료 페이지 도네이션 정보 반영 (Feature/donation complete UI)
  MobalMobal/MobalMobal/DonateComplete/DonateCompleteViewController.swift
  MobalMobal/MobalMobal/DonateMoney/DonateMoneyViewController.swift
  MobalMobal/MobalMobal/DonateMoney/DonateMoneyViewModel.swift
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewController.swift
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewModel.swift
  MobalMobal/MobalMobal/InputDonationMoney/InputDonationMoneyViewController.swift
Labels: UI 작업

#110 (#106) 키체인에 UserToken이 저장되어 있는지에 따른 플로우 체크 (Feature/login set user info)
  MobalMobal/MobalMobal.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MobalMobal/MobalMobal/AppDelegate.swift
  MobalMobal/MobalMobal/Common/KeychainManager.swift
  MobalMobal/MobalMobal/Common/UserInfo.swift
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewController.swift
  MobalMobal/MobalMobal/Login/Login+Firebase.swift
  MobalMobal/MobalMobal/Login/LoginViewController.swift
  MobalMobal/MobalMobal/Login/ViewModel/LoginViewModel.swift
  MobalMobal/MobalMobal/Main/MainViewController.swift
  MobalMobal/MobalMobal/Network/DoneService.swift
  MobalMobal/MobalMobal/ViewController.swift
Labels: UI 작업, 기능 추가

#132 (#127) profile, charging view network error시에 toast메세지
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewController.swift
  MobalMobal/MobalMobal/Main/MainViewModel.swift
  MobalMobal/MobalMobal/Network/DoneProvider.swift
  MobalMobal/MobalMobal/Network/DoneService.swift
  MobalMobal/MobalMobal/PointCharging/InputChargingPoint/ViewController/InputChargingPointViewController.swift
  MobalMobal/MobalMobal/PointCharging/PointChargingViewController.swift
  MobalMobal/MobalMobal/PointCharging/ViewModel/InputChargingPointViewModel.swift
  MobalMobal/MobalMobal/Profile/ViewController/ProfileViewController.swift
  MobalMobal/MobalMobal/Profile/ViewModel/ProfileMydonationViewModel.swift
  MobalMobal/MobalMobal/Profile/ViewModel/ProfileViewModel.swift
  MobalMobal/Podfile
Labels: 기능 추가

#140 🐛 (#138) seoyoungQA complete
  MobalMobal/MobalMobal/DonateMoney/DonateMoneyViewController.swift
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewController.swift
  MobalMobal/MobalMobal/InputDonationMoney/InputDonationMoneyViewController.swift
  MobalMobal/MobalMobal/PointCharging/PointChargingTableViewCell.swift
  MobalMobal/MobalMobal/PointCharging/PointChargingViewController.swift
  MobalMobal/MobalMobal/Profile/Cell/ProfileDonatingTableViewCell.swift
  MobalMobal/MobalMobal/Setting/SettingViewController.swift
Labels: 버그

#145 🐛 (#143) 후원 금액 직접 입력 후, 상세페이지로 돌아갔을 때 업데이트
  MobalMobal/MobalMobal/DonateMoney/DonateMoneyViewController.swift
  MobalMobal/MobalMobal/InputDonationMoney/InputDonationMoneyViewController.swift
Labels: 버그

#144 (#143) 버그수정(도네이션 생성, 생성완료, 상세 페이지)
  MobalMobal/MobalMobal/CreateDonation/CreateDonation.storyboard
  MobalMobal/MobalMobal/CreateDonation/CreateDonationViewController2.swift
  MobalMobal/MobalMobal/CreateDonation/ViewModel/CreateDonationViewModel.swift
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewController.swift
  MobalMobal/MobalMobal/MakeComplete/MakeCompleteViewController.swift
Labels: 버그

#157 (#150), (#155), (#156) 내 도네이션 network수정, 프로필 API call 리팩토링,프로필 새로고침, 종료된 도네이션 후원 막기
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewController.swift
  MobalMobal/MobalMobal/DonationDetail/DonationDetailViewModel.swift
  MobalMobal/MobalMobal/Main/MainViewModel.swift
  MobalMobal/MobalMobal/Profile/ViewController/ProfileViewController.swift
  MobalMobal/MobalMobal/Profile/ViewModel/ProfileViewModel.swift
Labels: 기능 추가, 버그

#168 (#167) 로그아웃 기능 구현
  MobalMobal/MobalMobal.xcodeproj/project.pbxproj
  MobalMobal/MobalMobal/Common/KeychainManager.swift
  MobalMobal/MobalMobal/Common/UserDefaultsKeys.swift
  MobalMobal/MobalMobal/Common/UserInfo.swift
  MobalMobal/MobalMobal/Login/ViewModel/LoginViewModel.swift
  MobalMobal/MobalMobal/Main/MainViewModel.swift
  MobalMobal/MobalMobal/Setting/SettingViewController.swift
Labels: UI 작업, 기능 추가
